# Generated by Django 5.2.6 on 2026-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="page_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
