# Generated by Django 5.2.6 on 2026-05-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_page_page_size_page_status_code_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="wcag_level",
            field=models.CharField(default="AA", max_length=3),
        ),
    ]
