# Generated by Django 5.2.6 on 2026-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_wcag_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="crawl_limit",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="project",
            name="estimated_pages",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
