# Generated by Django 5.2.6 on 2026-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_crawl_limit_project_estimated_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="ai_issues_found",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="ai_errors_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="ai_pages_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scan",
            name="ai_total_time",
            field=models.FloatField(default=0.0),
        ),
    ]
