# Generated by Django 6.0.5 on 2026-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_report_ai_issues_found_scan_ai_errors_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="crawl_depth",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="project",
            name="sitemap_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_health_report",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_legal_insights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_risk_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="compliance_20",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="report",
            name="compliance_21",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="report",
            name="compliance_22",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="report",
            name="level_a_issues",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="level_aa_issues",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="level_aaa_issues",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="score_operable",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="report",
            name="score_perceivable",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="report",
            name="score_robust",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="report",
            name="score_understandable",
            field=models.FloatField(default=100.0),
        ),
    ]
