# Generated by Django 6.0.5 on 2026-05-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_last_resent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
