# Generated by Django 6.0.5 on 2026-06-01 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_profile_is_email_verified_profile_otp_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="domain",
            field=models.URLField(max_length=2000),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("user", "domain"), name="unique_user_project_domain"
            ),
        ),
    ]
