# Generated by Django 6.0.5 on 2026-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_issue_fix_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="corrected_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="version",
            field=models.CharField(default="2.0,2.1,2.2", max_length=50),
        ),
    ]
